services:

  postgres-iam:
    image: postgres:17.0-alpine3.20
    container_name: postgres-iam
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_iam_data:/var/lib/postgresql/data
    ports:
      - "${EXTERNAL_POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - spaceship_network

  redis-iam:
    image: redis:7.2.5-alpine3.20
    container_name: redis-iam
    env_file:
      - .env
    ports:
      - "${EXTERNAL_REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - spaceship_network

  iam:
    image: iam:latest
    container_name: iam_service
    build:
      context: ../../../
      dockerfile: deploy/docker/iam/Dockerfile
    env_file:
      - .env
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      postgres-iam:
        condition: service_healthy
      redis-iam:
        condition: service_healthy
    networks:
      - spaceship_network
    restart: unless-stopped

volumes:
  postgres_iam_data:

networks:
  spaceship_network:
    external: true
    name: spaceship_network