// Code generated by ogen, DO NOT EDIT.
package order

type CancelOrderRes interface {
	cancelOrderRes()
}

type GetOrderByUUIDRes interface {
	getOrderByUUIDRes()
}

type PayOrderRes interface {
	payOrderRes()
}
