// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "order/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// InventoryClient is an autogenerated mock type for the InventoryClient type
type InventoryClient struct {
	mock.Mock
}

// ListParts provides a mock function with given fields: ctx, partUUIDs
func (_m *InventoryClient) ListParts(ctx context.Context, partUUIDs []uuid.UUID) ([]model.Part, error) {
	ret := _m.Called(ctx, partUUIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]model.Part, error)); ok {
		return rf(ctx, partUUIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []model.Part); ok {
		r0 = rf(ctx, partUUIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, partUUIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInventoryClient creates a new instance of InventoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryClient {
	mock := &InventoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
