// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockMongoConfig is an autogenerated mock type for the MongoConfig type
type MockMongoConfig struct {
	mock.Mock
}

type MockMongoConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoConfig) EXPECT() *MockMongoConfig_Expecter {
	return &MockMongoConfig_Expecter{mock: &_m.Mock}
}

// GetDatabaseName provides a mock function with no fields
func (_m *MockMongoConfig) GetDatabaseName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockMongoConfig_GetDatabaseName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseName'
type MockMongoConfig_GetDatabaseName_Call struct {
	*mock.Call
}

// GetDatabaseName is a helper method to define mock.On call
func (_e *MockMongoConfig_Expecter) GetDatabaseName() *MockMongoConfig_GetDatabaseName_Call {
	return &MockMongoConfig_GetDatabaseName_Call{Call: _e.mock.On("GetDatabaseName")}
}

func (_c *MockMongoConfig_GetDatabaseName_Call) Run(run func()) *MockMongoConfig_GetDatabaseName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMongoConfig_GetDatabaseName_Call) Return(_a0 string) *MockMongoConfig_GetDatabaseName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMongoConfig_GetDatabaseName_Call) RunAndReturn(run func() string) *MockMongoConfig_GetDatabaseName_Call {
	_c.Call.Return(run)
	return _c
}

// GetURI provides a mock function with no fields
func (_m *MockMongoConfig) GetURI() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetURI")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockMongoConfig_GetURI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURI'
type MockMongoConfig_GetURI_Call struct {
	*mock.Call
}

// GetURI is a helper method to define mock.On call
func (_e *MockMongoConfig_Expecter) GetURI() *MockMongoConfig_GetURI_Call {
	return &MockMongoConfig_GetURI_Call{Call: _e.mock.On("GetURI")}
}

func (_c *MockMongoConfig_GetURI_Call) Run(run func()) *MockMongoConfig_GetURI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMongoConfig_GetURI_Call) Return(_a0 string) *MockMongoConfig_GetURI_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMongoConfig_GetURI_Call) RunAndReturn(run func() string) *MockMongoConfig_GetURI_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMongoConfig creates a new instance of MockMongoConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoConfig {
	mock := &MockMongoConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
