openapi: 3.1.0
info:
  title: Spaceship-order API
  description: API для заказа корабля
  version: 1.0.0
x-ogen:
  target: ./pkg/api/spaceship-order/v1
  package: spaceship_order_v1
  clean: true

tags:
  - name: Spaceship
    description: Операции с заказами кораблей

paths:
  /api/v1/orders:
    $ref: ./paths/create_order.yaml
  
