// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderProducer is an autogenerated mock type for the OrderProducer type
type MockOrderProducer struct {
	mock.Mock
}

type MockOrderProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderProducer) EXPECT() *MockOrderProducer_Expecter {
	return &MockOrderProducer_Expecter{mock: &_m.Mock}
}

// PublishOrderPaid provides a mock function with given fields: ctx, orderUUID, userUUID, paymentMethod, transactionUUID
func (_m *MockOrderProducer) PublishOrderPaid(ctx context.Context, orderUUID string, userUUID string, paymentMethod string, transactionUUID string) error {
	ret := _m.Called(ctx, orderUUID, userUUID, paymentMethod, transactionUUID)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderPaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, orderUUID, userUUID, paymentMethod, transactionUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderProducer_PublishOrderPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOrderPaid'
type MockOrderProducer_PublishOrderPaid_Call struct {
	*mock.Call
}

// PublishOrderPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
//   - userUUID string
//   - paymentMethod string
//   - transactionUUID string
func (_e *MockOrderProducer_Expecter) PublishOrderPaid(ctx interface{}, orderUUID interface{}, userUUID interface{}, paymentMethod interface{}, transactionUUID interface{}) *MockOrderProducer_PublishOrderPaid_Call {
	return &MockOrderProducer_PublishOrderPaid_Call{Call: _e.mock.On("PublishOrderPaid", ctx, orderUUID, userUUID, paymentMethod, transactionUUID)}
}

func (_c *MockOrderProducer_PublishOrderPaid_Call) Run(run func(ctx context.Context, orderUUID string, userUUID string, paymentMethod string, transactionUUID string)) *MockOrderProducer_PublishOrderPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockOrderProducer_PublishOrderPaid_Call) Return(_a0 error) *MockOrderProducer_PublishOrderPaid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderProducer_PublishOrderPaid_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *MockOrderProducer_PublishOrderPaid_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderProducer creates a new instance of MockOrderProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderProducer {
	mock := &MockOrderProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
