// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "iam/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// GetByUUID provides a mock function with given fields: ctx, userUUID
func (_m *MockUserService) GetByUUID(ctx context.Context, userUUID string) (*model.User, error) {
	ret := _m.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, userUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, userUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type MockUserService_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
func (_e *MockUserService_Expecter) GetByUUID(ctx interface{}, userUUID interface{}) *MockUserService_GetByUUID_Call {
	return &MockUserService_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, userUUID)}
}

func (_c *MockUserService_GetByUUID_Call) Run(run func(ctx context.Context, userUUID string)) *MockUserService_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_GetByUUID_Call) Return(_a0 *model.User, _a1 error) *MockUserService_GetByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetByUUID_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *MockUserService_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, user, rawPassword
func (_m *MockUserService) Register(ctx context.Context, user *model.User, rawPassword string) (string, error) {
	ret := _m.Called(ctx, user, rawPassword)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User, string) (string, error)); ok {
		return rf(ctx, user, rawPassword)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User, string) string); ok {
		r0 = rf(ctx, user, rawPassword)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User, string) error); ok {
		r1 = rf(ctx, user, rawPassword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
//   - rawPassword string
func (_e *MockUserService_Expecter) Register(ctx interface{}, user interface{}, rawPassword interface{}) *MockUserService_Register_Call {
	return &MockUserService_Register_Call{Call: _e.mock.On("Register", ctx, user, rawPassword)}
}

func (_c *MockUserService_Register_Call) Run(run func(ctx context.Context, user *model.User, rawPassword string)) *MockUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User), args[2].(string))
	})
	return _c
}

func (_c *MockUserService_Register_Call) Return(_a0 string, _a1 error) *MockUserService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Register_Call) RunAndReturn(run func(context.Context, *model.User, string) (string, error)) *MockUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
