// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// OrderHttpConfig is an autogenerated mock type for the OrderHttpConfig type
type OrderHttpConfig struct {
	mock.Mock
}

// GetAddress provides a mock function with no fields
func (_m *OrderHttpConfig) GetAddress() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAddress")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetReadTimeout provides a mock function with no fields
func (_m *OrderHttpConfig) GetReadTimeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetReadTimeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// NewOrderHttpConfig creates a new instance of OrderHttpConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderHttpConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderHttpConfig {
	mock := &OrderHttpConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
