// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PostgresConfig is an autogenerated mock type for the PostgresConfig type
type PostgresConfig struct {
	mock.Mock
}

// Dsn provides a mock function with no fields
func (_m *PostgresConfig) Dsn() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dsn")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MigrationDir provides a mock function with no fields
func (_m *PostgresConfig) MigrationDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MigrationDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewPostgresConfig creates a new instance of PostgresConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostgresConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostgresConfig {
	mock := &PostgresConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
