// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OrderProducer is an autogenerated mock type for the OrderProducer type
type OrderProducer struct {
	mock.Mock
}

// PublishOrderPaid provides a mock function with given fields: ctx, orderUUID, userUUID, paymentMethod, transactionUUID
func (_m *OrderProducer) PublishOrderPaid(ctx context.Context, orderUUID string, userUUID string, paymentMethod string, transactionUUID string) error {
	ret := _m.Called(ctx, orderUUID, userUUID, paymentMethod, transactionUUID)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderPaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, orderUUID, userUUID, paymentMethod, transactionUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderProducer creates a new instance of OrderProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderProducer {
	mock := &OrderProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
