// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LoggerConfig is an autogenerated mock type for the LoggerConfig type
type LoggerConfig struct {
	mock.Mock
}

// LogAsJSON provides a mock function with no fields
func (_m *LoggerConfig) LogAsJSON() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LogAsJSON")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LogLevel provides a mock function with no fields
func (_m *LoggerConfig) LogLevel() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LogLevel")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewLoggerConfig creates a new instance of LoggerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerConfig {
	mock := &LoggerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
