syntax = "proto3";

package common.v1;

option go_package = "spaceship-orders/shared/pkg/proto/common/v1;commonv1";
// Способ уведомления пользователя
message NotificationMethod {
  string provider_name = 1; // например, "telegram", "email"
  string target = 2;        // адрес получателя (email или chat_id)
}

// Общая сущность пользователя, которая кладется в контекст
message User {
  string user_uuid = 1;
  string login = 2;
  string email = 3;
  repeated NotificationMethod notification_methods = 4;
}