services:
  # === Брокер сообщений Kafka ===
  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka
    ports:
      - "${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:${KAFKA_CONTROLLER_PORT}"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_INTERNAL_PORT},PLAINTEXT_EXTERNAL://0.0.0.0:${KAFKA_EXTERNAL_PORT},CONTROLLER://0.0.0.0:${KAFKA_CONTROLLER_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_INTERNAL_PORT},PLAINTEXT_EXTERNAL://localhost:${KAFKA_EXTERNAL_PORT},CONTROLLER://kafka:${KAFKA_CONTROLLER_PORT}

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/127.0.0.1/${KAFKA_INTERNAL_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
    networks:
      - spaceship_network

  # === Панель управления Kafka UI ===
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:${KAFKA_INTERNAL_PORT}"
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
    networks:
      - spaceship_network

  # === Сервис Оплаты (Заглушка) ===
  payment_app:
    image: payment:latest
    container_name: payment_service
    build:
      context: ../../../
      dockerfile: deploy/docker/payment/Dockerfile
    ports:
      - "50052:50052"
    env_file:
      - ../payment/.env
    environment:
      - GRPC_HOST=0.0.0.0
    networks:
      - spaceship_network
    restart: unless-stopped

  # === Сервис Сборки Кораблей (Assembly) ===
  assembly_app:
    image: assembly:latest
    container_name: assembly_service
    build:
      context: ../../../
      dockerfile: deploy/docker/assembly/Dockerfile
    env_file:
      - ../assembly/.env
    environment:
      - KAFKA_BROKERS=kafka:${KAFKA_INTERNAL_PORT:-29092}
      - KAFKA_ORDER_PAID_TOPIC=order-paid
      - KAFKA_ORDER_PAID_GROUP_ID=assembly-group
      - KAFKA_SHIP_ASSEMBLED_TOPIC=ship-assembled
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - spaceship_network
    restart: unless-stopped

volumes:
  kafka_data:

networks:
  spaceship_network:
    name: spaceship_network
    external: false