// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPostgresConfig is an autogenerated mock type for the PostgresConfig type
type MockPostgresConfig struct {
	mock.Mock
}

type MockPostgresConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgresConfig) EXPECT() *MockPostgresConfig_Expecter {
	return &MockPostgresConfig_Expecter{mock: &_m.Mock}
}

// Dsn provides a mock function with no fields
func (_m *MockPostgresConfig) Dsn() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dsn")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPostgresConfig_Dsn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dsn'
type MockPostgresConfig_Dsn_Call struct {
	*mock.Call
}

// Dsn is a helper method to define mock.On call
func (_e *MockPostgresConfig_Expecter) Dsn() *MockPostgresConfig_Dsn_Call {
	return &MockPostgresConfig_Dsn_Call{Call: _e.mock.On("Dsn")}
}

func (_c *MockPostgresConfig_Dsn_Call) Run(run func()) *MockPostgresConfig_Dsn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresConfig_Dsn_Call) Return(_a0 string) *MockPostgresConfig_Dsn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostgresConfig_Dsn_Call) RunAndReturn(run func() string) *MockPostgresConfig_Dsn_Call {
	_c.Call.Return(run)
	return _c
}

// MigrationDir provides a mock function with no fields
func (_m *MockPostgresConfig) MigrationDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MigrationDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPostgresConfig_MigrationDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrationDir'
type MockPostgresConfig_MigrationDir_Call struct {
	*mock.Call
}

// MigrationDir is a helper method to define mock.On call
func (_e *MockPostgresConfig_Expecter) MigrationDir() *MockPostgresConfig_MigrationDir_Call {
	return &MockPostgresConfig_MigrationDir_Call{Call: _e.mock.On("MigrationDir")}
}

func (_c *MockPostgresConfig_MigrationDir_Call) Run(run func()) *MockPostgresConfig_MigrationDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresConfig_MigrationDir_Call) Return(_a0 string) *MockPostgresConfig_MigrationDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostgresConfig_MigrationDir_Call) RunAndReturn(run func() string) *MockPostgresConfig_MigrationDir_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostgresConfig creates a new instance of MockPostgresConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgresConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgresConfig {
	mock := &MockPostgresConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
