// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockOrderPaidProducerConfig is an autogenerated mock type for the OrderPaidProducerConfig type
type MockOrderPaidProducerConfig struct {
	mock.Mock
}

type MockOrderPaidProducerConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderPaidProducerConfig) EXPECT() *MockOrderPaidProducerConfig_Expecter {
	return &MockOrderPaidProducerConfig_Expecter{mock: &_m.Mock}
}

// PaidTopic provides a mock function with no fields
func (_m *MockOrderPaidProducerConfig) PaidTopic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PaidTopic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOrderPaidProducerConfig_PaidTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PaidTopic'
type MockOrderPaidProducerConfig_PaidTopic_Call struct {
	*mock.Call
}

// PaidTopic is a helper method to define mock.On call
func (_e *MockOrderPaidProducerConfig_Expecter) PaidTopic() *MockOrderPaidProducerConfig_PaidTopic_Call {
	return &MockOrderPaidProducerConfig_PaidTopic_Call{Call: _e.mock.On("PaidTopic")}
}

func (_c *MockOrderPaidProducerConfig_PaidTopic_Call) Run(run func()) *MockOrderPaidProducerConfig_PaidTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderPaidProducerConfig_PaidTopic_Call) Return(_a0 string) *MockOrderPaidProducerConfig_PaidTopic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderPaidProducerConfig_PaidTopic_Call) RunAndReturn(run func() string) *MockOrderPaidProducerConfig_PaidTopic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderPaidProducerConfig creates a new instance of MockOrderPaidProducerConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderPaidProducerConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderPaidProducerConfig {
	mock := &MockOrderPaidProducerConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
