// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderHttpConfig is an autogenerated mock type for the OrderHttpConfig type
type MockOrderHttpConfig struct {
	mock.Mock
}

type MockOrderHttpConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderHttpConfig) EXPECT() *MockOrderHttpConfig_Expecter {
	return &MockOrderHttpConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *MockOrderHttpConfig) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOrderHttpConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockOrderHttpConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockOrderHttpConfig_Expecter) Address() *MockOrderHttpConfig_Address_Call {
	return &MockOrderHttpConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockOrderHttpConfig_Address_Call) Run(run func()) *MockOrderHttpConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderHttpConfig_Address_Call) Return(_a0 string) *MockOrderHttpConfig_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderHttpConfig_Address_Call) RunAndReturn(run func() string) *MockOrderHttpConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// ReadTimeout provides a mock function with no fields
func (_m *MockOrderHttpConfig) ReadTimeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadTimeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockOrderHttpConfig_ReadTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTimeout'
type MockOrderHttpConfig_ReadTimeout_Call struct {
	*mock.Call
}

// ReadTimeout is a helper method to define mock.On call
func (_e *MockOrderHttpConfig_Expecter) ReadTimeout() *MockOrderHttpConfig_ReadTimeout_Call {
	return &MockOrderHttpConfig_ReadTimeout_Call{Call: _e.mock.On("ReadTimeout")}
}

func (_c *MockOrderHttpConfig_ReadTimeout_Call) Run(run func()) *MockOrderHttpConfig_ReadTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderHttpConfig_ReadTimeout_Call) Return(_a0 time.Duration) *MockOrderHttpConfig_ReadTimeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderHttpConfig_ReadTimeout_Call) RunAndReturn(run func() time.Duration) *MockOrderHttpConfig_ReadTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderHttpConfig creates a new instance of MockOrderHttpConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderHttpConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderHttpConfig {
	mock := &MockOrderHttpConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
