// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "order/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, payment
func (_m *MockPaymentRepository) Create(ctx context.Context, payment *model.Payment) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Payment) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPaymentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *model.Payment
func (_e *MockPaymentRepository_Expecter) Create(ctx interface{}, payment interface{}) *MockPaymentRepository_Create_Call {
	return &MockPaymentRepository_Create_Call{Call: _e.mock.On("Create", ctx, payment)}
}

func (_c *MockPaymentRepository_Create_Call) Run(run func(ctx context.Context, payment *model.Payment)) *MockPaymentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Payment))
	})
	return _c
}

func (_c *MockPaymentRepository_Create_Call) Return(_a0 error) *MockPaymentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Payment) error) *MockPaymentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, paymentUUID
func (_m *MockPaymentRepository) Get(ctx context.Context, paymentUUID string) (*model.Payment, error) {
	ret := _m.Called(ctx, paymentUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Payment, error)); ok {
		return rf(ctx, paymentUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Payment); ok {
		r0 = rf(ctx, paymentUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPaymentRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentUUID string
func (_e *MockPaymentRepository_Expecter) Get(ctx interface{}, paymentUUID interface{}) *MockPaymentRepository_Get_Call {
	return &MockPaymentRepository_Get_Call{Call: _e.mock.On("Get", ctx, paymentUUID)}
}

func (_c *MockPaymentRepository_Get_Call) Run(run func(ctx context.Context, paymentUUID string)) *MockPaymentRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentRepository_Get_Call) Return(_a0 *model.Payment, _a1 error) *MockPaymentRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*model.Payment, error)) *MockPaymentRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOrder provides a mock function with given fields: ctx, orderUUID
func (_m *MockPaymentRepository) ListByOrder(ctx context.Context, orderUUID string) ([]*model.Payment, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrder")
	}

	var r0 []*model.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Payment, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Payment); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_ListByOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOrder'
type MockPaymentRepository_ListByOrder_Call struct {
	*mock.Call
}

// ListByOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID string
func (_e *MockPaymentRepository_Expecter) ListByOrder(ctx interface{}, orderUUID interface{}) *MockPaymentRepository_ListByOrder_Call {
	return &MockPaymentRepository_ListByOrder_Call{Call: _e.mock.On("ListByOrder", ctx, orderUUID)}
}

func (_c *MockPaymentRepository_ListByOrder_Call) Run(run func(ctx context.Context, orderUUID string)) *MockPaymentRepository_ListByOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentRepository_ListByOrder_Call) Return(_a0 []*model.Payment, _a1 error) *MockPaymentRepository_ListByOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_ListByOrder_Call) RunAndReturn(run func(context.Context, string) ([]*model.Payment, error)) *MockPaymentRepository_ListByOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
