// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "order/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPartRepository is an autogenerated mock type for the PartRepository type
type MockPartRepository struct {
	mock.Mock
}

type MockPartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPartRepository) EXPECT() *MockPartRepository_Expecter {
	return &MockPartRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, part
func (_m *MockPartRepository) Create(ctx context.Context, part *model.Part) error {
	ret := _m.Called(ctx, part)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Part) error); ok {
		r0 = rf(ctx, part)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPartRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPartRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - part *model.Part
func (_e *MockPartRepository_Expecter) Create(ctx interface{}, part interface{}) *MockPartRepository_Create_Call {
	return &MockPartRepository_Create_Call{Call: _e.mock.On("Create", ctx, part)}
}

func (_c *MockPartRepository_Create_Call) Run(run func(ctx context.Context, part *model.Part)) *MockPartRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Part))
	})
	return _c
}

func (_c *MockPartRepository_Create_Call) Return(_a0 error) *MockPartRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPartRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Part) error) *MockPartRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementStock provides a mock function with given fields: ctx, partUUID, qty
func (_m *MockPartRepository) DecrementStock(ctx context.Context, partUUID string, qty int) error {
	ret := _m.Called(ctx, partUUID, qty)

	if len(ret) == 0 {
		panic("no return value specified for DecrementStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, partUUID, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPartRepository_DecrementStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementStock'
type MockPartRepository_DecrementStock_Call struct {
	*mock.Call
}

// DecrementStock is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUID string
//   - qty int
func (_e *MockPartRepository_Expecter) DecrementStock(ctx interface{}, partUUID interface{}, qty interface{}) *MockPartRepository_DecrementStock_Call {
	return &MockPartRepository_DecrementStock_Call{Call: _e.mock.On("DecrementStock", ctx, partUUID, qty)}
}

func (_c *MockPartRepository_DecrementStock_Call) Run(run func(ctx context.Context, partUUID string, qty int)) *MockPartRepository_DecrementStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockPartRepository_DecrementStock_Call) Return(_a0 error) *MockPartRepository_DecrementStock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPartRepository_DecrementStock_Call) RunAndReturn(run func(context.Context, string, int) error) *MockPartRepository_DecrementStock_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, partUUID
func (_m *MockPartRepository) Delete(ctx context.Context, partUUID string) error {
	ret := _m.Called(ctx, partUUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, partUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPartRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPartRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUID string
func (_e *MockPartRepository_Expecter) Delete(ctx interface{}, partUUID interface{}) *MockPartRepository_Delete_Call {
	return &MockPartRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, partUUID)}
}

func (_c *MockPartRepository_Delete_Call) Run(run func(ctx context.Context, partUUID string)) *MockPartRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPartRepository_Delete_Call) Return(_a0 error) *MockPartRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPartRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockPartRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, partUUID
func (_m *MockPartRepository) Get(ctx context.Context, partUUID string) (*model.Part, error) {
	ret := _m.Called(ctx, partUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Part, error)); ok {
		return rf(ctx, partUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = rf(ctx, partUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, partUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPartRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPartRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUID string
func (_e *MockPartRepository_Expecter) Get(ctx interface{}, partUUID interface{}) *MockPartRepository_Get_Call {
	return &MockPartRepository_Get_Call{Call: _e.mock.On("Get", ctx, partUUID)}
}

func (_c *MockPartRepository_Get_Call) Run(run func(ctx context.Context, partUUID string)) *MockPartRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPartRepository_Get_Call) Return(_a0 *model.Part, _a1 error) *MockPartRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPartRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*model.Part, error)) *MockPartRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUIDs provides a mock function with given fields: ctx, partUUIDs
func (_m *MockPartRepository) GetByUUIDs(ctx context.Context, partUUIDs []uuid.UUID) ([]*model.Part, error) {
	ret := _m.Called(ctx, partUUIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUIDs")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*model.Part, error)); ok {
		return rf(ctx, partUUIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*model.Part); ok {
		r0 = rf(ctx, partUUIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, partUUIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPartRepository_GetByUUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUIDs'
type MockPartRepository_GetByUUIDs_Call struct {
	*mock.Call
}

// GetByUUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUIDs []uuid.UUID
func (_e *MockPartRepository_Expecter) GetByUUIDs(ctx interface{}, partUUIDs interface{}) *MockPartRepository_GetByUUIDs_Call {
	return &MockPartRepository_GetByUUIDs_Call{Call: _e.mock.On("GetByUUIDs", ctx, partUUIDs)}
}

func (_c *MockPartRepository_GetByUUIDs_Call) Run(run func(ctx context.Context, partUUIDs []uuid.UUID)) *MockPartRepository_GetByUUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockPartRepository_GetByUUIDs_Call) Return(_a0 []*model.Part, _a1 error) *MockPartRepository_GetByUUIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPartRepository_GetByUUIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]*model.Part, error)) *MockPartRepository_GetByUUIDs_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockPartRepository) List(ctx context.Context) ([]*model.Part, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Part, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Part); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPartRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPartRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPartRepository_Expecter) List(ctx interface{}) *MockPartRepository_List_Call {
	return &MockPartRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockPartRepository_List_Call) Run(run func(ctx context.Context)) *MockPartRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPartRepository_List_Call) Return(_a0 []*model.Part, _a1 error) *MockPartRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPartRepository_List_Call) RunAndReturn(run func(context.Context) ([]*model.Part, error)) *MockPartRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, part
func (_m *MockPartRepository) Update(ctx context.Context, part *model.Part) error {
	ret := _m.Called(ctx, part)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Part) error); ok {
		r0 = rf(ctx, part)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPartRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPartRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - part *model.Part
func (_e *MockPartRepository_Expecter) Update(ctx interface{}, part interface{}) *MockPartRepository_Update_Call {
	return &MockPartRepository_Update_Call{Call: _e.mock.On("Update", ctx, part)}
}

func (_c *MockPartRepository_Update_Call) Run(run func(ctx context.Context, part *model.Part)) *MockPartRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Part))
	})
	return _c
}

func (_c *MockPartRepository_Update_Call) Return(_a0 error) *MockPartRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPartRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Part) error) *MockPartRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPartRepository creates a new instance of MockPartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPartRepository {
	mock := &MockPartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
