// Code generated by ogen, DO NOT EDIT.

package order

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrder implements cancelOrder operation.
//
// Отмена заказа.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r CancelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements createOrder operation.
//
// Создание заказа.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePart implements createPart operation.
//
// Создать деталь.
//
// POST /api/v1/parts
func (UnimplementedHandler) CreatePart(ctx context.Context, req *CreatePartRequest) (r CreatePartRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOrder implements deleteOrder operation.
//
// Удалить заказ.
//
// DELETE /api/v1/orders/{order_uuid}
func (UnimplementedHandler) DeleteOrder(ctx context.Context, params DeleteOrderParams) (r DeleteOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePart implements deletePart operation.
//
// Удалить деталь.
//
// DELETE /api/v1/parts/{part_uuid}
func (UnimplementedHandler) DeletePart(ctx context.Context, params DeletePartParams) (r DeletePartRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderByUUID implements getOrderByUUID operation.
//
// Получить заказ по UUID.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrderByUUID(ctx context.Context, params GetOrderByUUIDParams) (r GetOrderByUUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPartByUUID implements getPartByUUID operation.
//
// Получить деталь по UUID.
//
// GET /api/v1/parts/{part_uuid}
func (UnimplementedHandler) GetPartByUUID(ctx context.Context, params GetPartByUUIDParams) (r GetPartByUUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPaymentByUUID implements getPaymentByUUID operation.
//
// Получить платёж по UUID.
//
// GET /api/v1/payments/{payment_uuid}
func (UnimplementedHandler) GetPaymentByUUID(ctx context.Context, params GetPaymentByUUIDParams) (r GetPaymentByUUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOrders implements listOrders operation.
//
// Список заказов.
//
// GET /api/v1/orders
func (UnimplementedHandler) ListOrders(ctx context.Context) (r ListOrdersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListParts implements listParts operation.
//
// Список деталей каталога.
//
// GET /api/v1/parts
func (UnimplementedHandler) ListParts(ctx context.Context) (r ListPartsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPaymentsByOrder implements listPaymentsByOrder operation.
//
// Список платежей по заказу.
//
// GET /api/v1/orders/{order_uuid}/payments
func (UnimplementedHandler) ListPaymentsByOrder(ctx context.Context, params ListPaymentsByOrderParams) (r ListPaymentsByOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements payOrder operation.
//
// Оплата заказа.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePart implements updatePart operation.
//
// Обновить деталь.
//
// PUT /api/v1/parts/{part_uuid}
func (UnimplementedHandler) UpdatePart(ctx context.Context, req *UpdatePartRequest, params UpdatePartParams) (r UpdatePartRes, _ error) {
	return r, ht.ErrNotImplemented
}
