// Code generated by ogen, DO NOT EDIT.

package order

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelOrderOperation    OperationName = "CancelOrder"
	CreateOrderOperation    OperationName = "CreateOrder"
	DeleteOrderOperation    OperationName = "DeleteOrder"
	GetOrderByUUIDOperation OperationName = "GetOrderByUUID"
	ListOrdersOperation     OperationName = "ListOrders"
	PayOrderOperation       OperationName = "PayOrder"
)
