// Code generated by ogen, DO NOT EDIT.

package order

// setDefaults set default value of fields.
func (s *CreatePartRequest) setDefaults() {
	{
		val := string("GENERAL")
		s.Category.SetTo(val)
	}
	{
		val := int(0)
		s.InStock.SetTo(val)
	}
}
