// Code generated by ogen, DO NOT EDIT.
package order

type CancelOrderRes interface {
	cancelOrderRes()
}

type CreateOrderRes interface {
	createOrderRes()
}

type DeleteOrderRes interface {
	deleteOrderRes()
}

type GetOrderByUUIDRes interface {
	getOrderByUUIDRes()
}

type ListOrdersRes interface {
	listOrdersRes()
}

type PayOrderRes interface {
	payOrderRes()
}
