// Code generated by ogen, DO NOT EDIT.

package order

import (
	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type CancelOrderConflict GenericError

func (*CancelOrderConflict) cancelOrderRes() {}

// CancelOrderNoContent is response for CancelOrder operation.
type CancelOrderNoContent struct{}

func (*CancelOrderNoContent) cancelOrderRes() {}

type CancelOrderNotFound GenericError

func (*CancelOrderNotFound) cancelOrderRes() {}

type CreateOrderBadRequest GenericError

func (*CreateOrderBadRequest) createOrderRes() {}

type CreateOrderInternalServerError GenericError

func (*CreateOrderInternalServerError) createOrderRes() {}

// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	// Список UUID деталей, входящих в заказ.
	PartUuids []uuid.UUID `json:"part_uuids"`
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	OrderUUID  uuid.UUID `json:"order_uuid"`
	TotalPrice float64   `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

type CreatePartBadRequest GenericError

func (*CreatePartBadRequest) createPartRes() {}

type CreatePartInternalServerError GenericError

func (*CreatePartInternalServerError) createPartRes() {}

// Ref: #/components/schemas/create_part_request
type CreatePartRequest struct {
	Name     string    `json:"name"`
	Price    float64   `json:"price"`
	Category OptString `json:"category"`
	InStock  OptInt    `json:"in_stock"`
}

// GetName returns the value of Name.
func (s *CreatePartRequest) GetName() string {
	return s.Name
}

// GetPrice returns the value of Price.
func (s *CreatePartRequest) GetPrice() float64 {
	return s.Price
}

// GetCategory returns the value of Category.
func (s *CreatePartRequest) GetCategory() OptString {
	return s.Category
}

// GetInStock returns the value of InStock.
func (s *CreatePartRequest) GetInStock() OptInt {
	return s.InStock
}

// SetName sets the value of Name.
func (s *CreatePartRequest) SetName(val string) {
	s.Name = val
}

// SetPrice sets the value of Price.
func (s *CreatePartRequest) SetPrice(val float64) {
	s.Price = val
}

// SetCategory sets the value of Category.
func (s *CreatePartRequest) SetCategory(val OptString) {
	s.Category = val
}

// SetInStock sets the value of InStock.
func (s *CreatePartRequest) SetInStock(val OptInt) {
	s.InStock = val
}

type DeleteOrderInternalServerError GenericError

func (*DeleteOrderInternalServerError) deleteOrderRes() {}

// DeleteOrderNoContent is response for DeleteOrder operation.
type DeleteOrderNoContent struct{}

func (*DeleteOrderNoContent) deleteOrderRes() {}

type DeleteOrderNotFound GenericError

func (*DeleteOrderNotFound) deleteOrderRes() {}

type DeletePartInternalServerError GenericError

func (*DeletePartInternalServerError) deletePartRes() {}

// DeletePartNoContent is response for DeletePart operation.
type DeletePartNoContent struct{}

func (*DeletePartNoContent) deletePartRes() {}

type DeletePartNotFound GenericError

func (*DeletePartNotFound) deletePartRes() {}

// Ref: #/components/schemas/generic_error
type GenericError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val string) {
	s.Message = val
}

func (*GenericError) getOrderByUUIDRes() {}
func (*GenericError) listPartsRes()      {}

type GetPartByUUIDInternalServerError GenericError

func (*GetPartByUUIDInternalServerError) getPartByUUIDRes() {}

type GetPartByUUIDNotFound GenericError

func (*GetPartByUUIDNotFound) getPartByUUIDRes() {}

type GetPaymentByUUIDInternalServerError GenericError

func (*GetPaymentByUUIDInternalServerError) getPaymentByUUIDRes() {}

type GetPaymentByUUIDNotFound GenericError

func (*GetPaymentByUUIDNotFound) getPaymentByUUIDRes() {}

type ListOrdersBadRequest GenericError

func (*ListOrdersBadRequest) listOrdersRes() {}

type ListOrdersInternalServerError GenericError

func (*ListOrdersInternalServerError) listOrdersRes() {}

type ListOrdersOKApplicationJSON []OrderDto

func (*ListOrdersOKApplicationJSON) listOrdersRes() {}

type ListPartsOKApplicationJSON []PartDto

func (*ListPartsOKApplicationJSON) listPartsRes() {}

type ListPaymentsByOrderInternalServerError GenericError

func (*ListPaymentsByOrderInternalServerError) listPaymentsByOrderRes() {}

type ListPaymentsByOrderNotFound GenericError

func (*ListPaymentsByOrderNotFound) listPaymentsByOrderRes() {}

type ListPaymentsByOrderOKApplicationJSON []PaymentDto

func (*ListPaymentsByOrderOKApplicationJSON) listPaymentsByOrderRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilPaymentMethod returns new OptNilPaymentMethod with value set to v.
func NewOptNilPaymentMethod(v PaymentMethod) OptNilPaymentMethod {
	return OptNilPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptNilPaymentMethod is optional nullable PaymentMethod.
type OptNilPaymentMethod struct {
	Value PaymentMethod
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilPaymentMethod was set.
func (o OptNilPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilPaymentMethod) Reset() {
	var v PaymentMethod
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilPaymentMethod) SetTo(v PaymentMethod) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilPaymentMethod) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilPaymentMethod) SetToNull() {
	o.Set = true
	o.Null = true
	var v PaymentMethod
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilPaymentMethod) Get() (v PaymentMethod, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilPaymentMethod) Or(d PaymentMethod) PaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/order_dto
type OrderDto struct {
	// Уникальный идентификатор заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// UUID пользователя.
	UserUUID uuid.UUID `json:"user_uuid"`
	// Список UUID деталей (развёрнутый по quantity).
	PartUuids []uuid.UUID `json:"part_uuids"`
	// Позиции заказа.
	Items []OrderItemDto `json:"items"`
	// Итоговая стоимость.
	TotalPrice float64 `json:"total_price"`
	// UUID транзакции/платежа (если оплачен).
	TransactionUUID OptUUID `json:"transaction_uuid"`
	// Способ оплаты (присутствует, только если статус PAID).
	PaymentMethod OptNilPaymentMethod `json:"payment_method"`
	Status        OrderStatus         `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *OrderDto) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *OrderDto) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *OrderDto) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetItems returns the value of Items.
func (s *OrderDto) GetItems() []OrderItemDto {
	return s.Items
}

// GetTotalPrice returns the value of TotalPrice.
func (s *OrderDto) GetTotalPrice() float64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *OrderDto) GetTransactionUUID() OptUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *OrderDto) GetPaymentMethod() OptNilPaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *OrderDto) GetStatus() OrderStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *OrderDto) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *OrderDto) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *OrderDto) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetItems sets the value of Items.
func (s *OrderDto) SetItems(val []OrderItemDto) {
	s.Items = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *OrderDto) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *OrderDto) SetTransactionUUID(val OptUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *OrderDto) SetPaymentMethod(val OptNilPaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *OrderDto) SetStatus(val OrderStatus) {
	s.Status = val
}

func (*OrderDto) getOrderByUUIDRes() {}

// Ref: #/components/schemas/order_item_dto
type OrderItemDto struct {
	PartUUID  uuid.UUID `json:"part_uuid"`
	Quantity  int       `json:"quantity"`
	UnitPrice float64   `json:"unit_price"`
}

// GetPartUUID returns the value of PartUUID.
func (s *OrderItemDto) GetPartUUID() uuid.UUID {
	return s.PartUUID
}

// GetQuantity returns the value of Quantity.
func (s *OrderItemDto) GetQuantity() int {
	return s.Quantity
}

// GetUnitPrice returns the value of UnitPrice.
func (s *OrderItemDto) GetUnitPrice() float64 {
	return s.UnitPrice
}

// SetPartUUID sets the value of PartUUID.
func (s *OrderItemDto) SetPartUUID(val uuid.UUID) {
	s.PartUUID = val
}

// SetQuantity sets the value of Quantity.
func (s *OrderItemDto) SetQuantity(val int) {
	s.Quantity = val
}

// SetUnitPrice sets the value of UnitPrice.
func (s *OrderItemDto) SetUnitPrice(val float64) {
	s.UnitPrice = val
}

// Текущий статус жизненного цикла заказа.
// Ref: #/components/schemas/order_status
type OrderStatus string

const (
	OrderStatusPENDINGPAYMENT OrderStatus = "PENDING_PAYMENT"
	OrderStatusPAID           OrderStatus = "PAID"
	OrderStatusCANCELLED      OrderStatus = "CANCELLED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusPENDINGPAYMENT,
		OrderStatusPAID,
		OrderStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusPAID:
		return []byte(s), nil
	case OrderStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusPENDINGPAYMENT:
		*s = OrderStatusPENDINGPAYMENT
		return nil
	case OrderStatusPAID:
		*s = OrderStatusPAID
		return nil
	case OrderStatusCANCELLED:
		*s = OrderStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/part_dto
type PartDto struct {
	PartUUID uuid.UUID `json:"part_uuid"`
	Name     string    `json:"name"`
	Price    float64   `json:"price"`
	Category string    `json:"category"`
	InStock  int       `json:"in_stock"`
}

// GetPartUUID returns the value of PartUUID.
func (s *PartDto) GetPartUUID() uuid.UUID {
	return s.PartUUID
}

// GetName returns the value of Name.
func (s *PartDto) GetName() string {
	return s.Name
}

// GetPrice returns the value of Price.
func (s *PartDto) GetPrice() float64 {
	return s.Price
}

// GetCategory returns the value of Category.
func (s *PartDto) GetCategory() string {
	return s.Category
}

// GetInStock returns the value of InStock.
func (s *PartDto) GetInStock() int {
	return s.InStock
}

// SetPartUUID sets the value of PartUUID.
func (s *PartDto) SetPartUUID(val uuid.UUID) {
	s.PartUUID = val
}

// SetName sets the value of Name.
func (s *PartDto) SetName(val string) {
	s.Name = val
}

// SetPrice sets the value of Price.
func (s *PartDto) SetPrice(val float64) {
	s.Price = val
}

// SetCategory sets the value of Category.
func (s *PartDto) SetCategory(val string) {
	s.Category = val
}

// SetInStock sets the value of InStock.
func (s *PartDto) SetInStock(val int) {
	s.InStock = val
}

func (*PartDto) createPartRes()    {}
func (*PartDto) getPartByUUIDRes() {}
func (*PartDto) updatePartRes()    {}

type PayOrderBadRequest GenericError

func (*PayOrderBadRequest) payOrderRes() {}

type PayOrderInternalServerError GenericError

func (*PayOrderInternalServerError) payOrderRes() {}

type PayOrderNotFound GenericError

func (*PayOrderNotFound) payOrderRes() {}

// Ref: #/components/schemas/pay_order_request
type PayOrderRequest struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #/components/schemas/pay_order_response
type PayOrderResponse struct {
	TransactionUUID uuid.UUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() uuid.UUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val uuid.UUID) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}

// Ref: #/components/schemas/payment_dto
type PaymentDto struct {
	PaymentUUID uuid.UUID     `json:"payment_uuid"`
	OrderUUID   uuid.UUID     `json:"order_uuid"`
	Amount      float64       `json:"amount"`
	Method      PaymentMethod `json:"method"`
	Status      PaymentStatus `json:"status"`
}

// GetPaymentUUID returns the value of PaymentUUID.
func (s *PaymentDto) GetPaymentUUID() uuid.UUID {
	return s.PaymentUUID
}

// GetOrderUUID returns the value of OrderUUID.
func (s *PaymentDto) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetAmount returns the value of Amount.
func (s *PaymentDto) GetAmount() float64 {
	return s.Amount
}

// GetMethod returns the value of Method.
func (s *PaymentDto) GetMethod() PaymentMethod {
	return s.Method
}

// GetStatus returns the value of Status.
func (s *PaymentDto) GetStatus() PaymentStatus {
	return s.Status
}

// SetPaymentUUID sets the value of PaymentUUID.
func (s *PaymentDto) SetPaymentUUID(val uuid.UUID) {
	s.PaymentUUID = val
}

// SetOrderUUID sets the value of OrderUUID.
func (s *PaymentDto) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetAmount sets the value of Amount.
func (s *PaymentDto) SetAmount(val float64) {
	s.Amount = val
}

// SetMethod sets the value of Method.
func (s *PaymentDto) SetMethod(val PaymentMethod) {
	s.Method = val
}

// SetStatus sets the value of Status.
func (s *PaymentDto) SetStatus(val PaymentStatus) {
	s.Status = val
}

func (*PaymentDto) getPaymentByUUIDRes() {}

// Способ оплаты заказа.
// Ref: #/components/schemas/payment_method
type PaymentMethod string

const (
	PaymentMethodUNKNOWN       PaymentMethod = "UNKNOWN"
	PaymentMethodCARD          PaymentMethod = "CARD"
	PaymentMethodSBP           PaymentMethod = "SBP"
	PaymentMethodCREDITCARD    PaymentMethod = "CREDIT_CARD"
	PaymentMethodINVESTORMONEY PaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodUNKNOWN,
		PaymentMethodCARD,
		PaymentMethodSBP,
		PaymentMethodCREDITCARD,
		PaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodUNKNOWN:
		return []byte(s), nil
	case PaymentMethodCARD:
		return []byte(s), nil
	case PaymentMethodSBP:
		return []byte(s), nil
	case PaymentMethodCREDITCARD:
		return []byte(s), nil
	case PaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodUNKNOWN:
		*s = PaymentMethodUNKNOWN
		return nil
	case PaymentMethodCARD:
		*s = PaymentMethodCARD
		return nil
	case PaymentMethodSBP:
		*s = PaymentMethodSBP
		return nil
	case PaymentMethodCREDITCARD:
		*s = PaymentMethodCREDITCARD
		return nil
	case PaymentMethodINVESTORMONEY:
		*s = PaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/payment_status
type PaymentStatus string

const (
	PaymentStatusPENDING   PaymentStatus = "PENDING"
	PaymentStatusSUCCEEDED PaymentStatus = "SUCCEEDED"
	PaymentStatusFAILED    PaymentStatus = "FAILED"
)

// AllValues returns all PaymentStatus values.
func (PaymentStatus) AllValues() []PaymentStatus {
	return []PaymentStatus{
		PaymentStatusPENDING,
		PaymentStatusSUCCEEDED,
		PaymentStatusFAILED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentStatus) MarshalText() ([]byte, error) {
	switch s {
	case PaymentStatusPENDING:
		return []byte(s), nil
	case PaymentStatusSUCCEEDED:
		return []byte(s), nil
	case PaymentStatusFAILED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentStatus) UnmarshalText(data []byte) error {
	switch PaymentStatus(data) {
	case PaymentStatusPENDING:
		*s = PaymentStatusPENDING
		return nil
	case PaymentStatusSUCCEEDED:
		*s = PaymentStatusSUCCEEDED
		return nil
	case PaymentStatusFAILED:
		*s = PaymentStatusFAILED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type UpdatePartBadRequest GenericError

func (*UpdatePartBadRequest) updatePartRes() {}

type UpdatePartInternalServerError GenericError

func (*UpdatePartInternalServerError) updatePartRes() {}

type UpdatePartNotFound GenericError

func (*UpdatePartNotFound) updatePartRes() {}

// Ref: #/components/schemas/update_part_request
type UpdatePartRequest struct {
	Name     string  `json:"name"`
	Price    float64 `json:"price"`
	Category string  `json:"category"`
	InStock  int     `json:"in_stock"`
}

// GetName returns the value of Name.
func (s *UpdatePartRequest) GetName() string {
	return s.Name
}

// GetPrice returns the value of Price.
func (s *UpdatePartRequest) GetPrice() float64 {
	return s.Price
}

// GetCategory returns the value of Category.
func (s *UpdatePartRequest) GetCategory() string {
	return s.Category
}

// GetInStock returns the value of InStock.
func (s *UpdatePartRequest) GetInStock() int {
	return s.InStock
}

// SetName sets the value of Name.
func (s *UpdatePartRequest) SetName(val string) {
	s.Name = val
}

// SetPrice sets the value of Price.
func (s *UpdatePartRequest) SetPrice(val float64) {
	s.Price = val
}

// SetCategory sets the value of Category.
func (s *UpdatePartRequest) SetCategory(val string) {
	s.Category = val
}

// SetInStock sets the value of InStock.
func (s *UpdatePartRequest) SetInStock(val int) {
	s.InStock = val
}
