// Code generated by ogen, DO NOT EDIT.

package order

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelOrderOperation         OperationName = "CancelOrder"
	CreateOrderOperation         OperationName = "CreateOrder"
	CreatePartOperation          OperationName = "CreatePart"
	DeleteOrderOperation         OperationName = "DeleteOrder"
	DeletePartOperation          OperationName = "DeletePart"
	GetOrderByUUIDOperation      OperationName = "GetOrderByUUID"
	GetPartByUUIDOperation       OperationName = "GetPartByUUID"
	GetPaymentByUUIDOperation    OperationName = "GetPaymentByUUID"
	ListOrdersOperation          OperationName = "ListOrders"
	ListPartsOperation           OperationName = "ListParts"
	ListPaymentsByOrderOperation OperationName = "ListPaymentsByOrder"
	PayOrderOperation            OperationName = "PayOrder"
	UpdatePartOperation          OperationName = "UpdatePart"
)
