// Code generated by ogen, DO NOT EDIT.

package iam

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// Login implements login operation.
	//
	// Вход пользователя.
	//
	// POST /api/v1/auth/login
	Login(ctx context.Context, req *LoginRequest) (LoginRes, error)
	// Logout implements logout operation.
	//
	// Выход (удаление сессии).
	//
	// POST /api/v1/auth/logout
	Logout(ctx context.Context, params LogoutParams) (LogoutRes, error)
	// Register implements register operation.
	//
	// Регистрация пользователя.
	//
	// POST /api/v1/auth/register
	Register(ctx context.Context, req *RegisterRequest) (RegisterRes, error)
	// Whoami implements whoami operation.
	//
	// Текущий пользователь по сессии.
	//
	// GET /api/v1/auth/whoami
	Whoami(ctx context.Context, params WhoamiParams) (WhoamiRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
