// Code generated by ogen, DO NOT EDIT.

package iam

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Login implements login operation.
//
// Вход пользователя.
//
// POST /api/v1/auth/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginRequest) (r LoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// Выход (удаление сессии).
//
// POST /api/v1/auth/logout
func (UnimplementedHandler) Logout(ctx context.Context, params LogoutParams) (r LogoutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Register implements register operation.
//
// Регистрация пользователя.
//
// POST /api/v1/auth/register
func (UnimplementedHandler) Register(ctx context.Context, req *RegisterRequest) (r RegisterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Whoami implements whoami operation.
//
// Текущий пользователь по сессии.
//
// GET /api/v1/auth/whoami
func (UnimplementedHandler) Whoami(ctx context.Context, params WhoamiParams) (r WhoamiRes, _ error) {
	return r, ht.ErrNotImplemented
}
