// Code generated by ogen, DO NOT EDIT.

package iam

import (
	"github.com/google/uuid"
)

// Ref: #/components/schemas/generic_error
type GenericError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val string) {
	s.Message = val
}

type LoginBadRequest GenericError

func (*LoginBadRequest) loginRes() {}

type LoginInternalServerError GenericError

func (*LoginInternalServerError) loginRes() {}

// Ref: #/components/schemas/login_request
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// GetLogin returns the value of Login.
func (s *LoginRequest) GetLogin() string {
	return s.Login
}

// GetPassword returns the value of Password.
func (s *LoginRequest) GetPassword() string {
	return s.Password
}

// SetLogin sets the value of Login.
func (s *LoginRequest) SetLogin(val string) {
	s.Login = val
}

// SetPassword sets the value of Password.
func (s *LoginRequest) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/login_response
type LoginResponse struct {
	// UUID сессии для заголовка X-Session-Uuid.
	SessionUUID uuid.UUID `json:"session_uuid"`
	User        UserDto   `json:"user"`
}

// GetSessionUUID returns the value of SessionUUID.
func (s *LoginResponse) GetSessionUUID() uuid.UUID {
	return s.SessionUUID
}

// GetUser returns the value of User.
func (s *LoginResponse) GetUser() UserDto {
	return s.User
}

// SetSessionUUID sets the value of SessionUUID.
func (s *LoginResponse) SetSessionUUID(val uuid.UUID) {
	s.SessionUUID = val
}

// SetUser sets the value of User.
func (s *LoginResponse) SetUser(val UserDto) {
	s.User = val
}

func (*LoginResponse) loginRes() {}

type LoginUnauthorized GenericError

func (*LoginUnauthorized) loginRes() {}

type LogoutInternalServerError GenericError

func (*LogoutInternalServerError) logoutRes() {}

// LogoutNoContent is response for Logout operation.
type LogoutNoContent struct{}

func (*LogoutNoContent) logoutRes() {}

type LogoutUnauthorized GenericError

func (*LogoutUnauthorized) logoutRes() {}

type RegisterBadRequest GenericError

func (*RegisterBadRequest) registerRes() {}

type RegisterConflict GenericError

func (*RegisterConflict) registerRes() {}

type RegisterInternalServerError GenericError

func (*RegisterInternalServerError) registerRes() {}

// Ref: #/components/schemas/register_request
type RegisterRequest struct {
	// Логин пользователя.
	Login string `json:"login"`
	// Пароль.
	Password string `json:"password"`
}

// GetLogin returns the value of Login.
func (s *RegisterRequest) GetLogin() string {
	return s.Login
}

// GetPassword returns the value of Password.
func (s *RegisterRequest) GetPassword() string {
	return s.Password
}

// SetLogin sets the value of Login.
func (s *RegisterRequest) SetLogin(val string) {
	s.Login = val
}

// SetPassword sets the value of Password.
func (s *RegisterRequest) SetPassword(val string) {
	s.Password = val
}

// Ref: #/components/schemas/user_dto
type UserDto struct {
	UserUUID uuid.UUID `json:"user_uuid"`
	Login    string    `json:"login"`
}

// GetUserUUID returns the value of UserUUID.
func (s *UserDto) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetLogin returns the value of Login.
func (s *UserDto) GetLogin() string {
	return s.Login
}

// SetUserUUID sets the value of UserUUID.
func (s *UserDto) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetLogin sets the value of Login.
func (s *UserDto) SetLogin(val string) {
	s.Login = val
}

func (*UserDto) registerRes() {}
func (*UserDto) whoamiRes()   {}

type WhoamiInternalServerError GenericError

func (*WhoamiInternalServerError) whoamiRes() {}

type WhoamiUnauthorized GenericError

func (*WhoamiUnauthorized) whoamiRes() {}
