// Code generated by ogen, DO NOT EDIT.
package iam

type LoginRes interface {
	loginRes()
}

type LogoutRes interface {
	logoutRes()
}

type RegisterRes interface {
	registerRes()
}

type WhoamiRes interface {
	whoamiRes()
}
