// Code generated by ogen, DO NOT EDIT.

package iam

// OperationName is the ogen operation name
type OperationName = string

const (
	LoginOperation    OperationName = "Login"
	LogoutOperation   OperationName = "Logout"
	RegisterOperation OperationName = "Register"
	WhoamiOperation   OperationName = "Whoami"
)
