services:
  inventory_db:
    image: mongo:7.0
    container_name: inventory_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase $${MONGO_AUTH_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - spaceship_network
    volumes:
      - inventory_mongo_data:/data/db

  inventory_app:
    image: inventory:latest
    container_name: inventory_service
    build:
      context: ../../../
      dockerfile: deploy/docker/inventory/Dockerfile
    env_file:
      - .env
    ports:
      - "${GRPC_PORT:-50051}:${GRPC_PORT:-50051}"
    environment:
      - GRPC_PORT=${GRPC_PORT}
      - MONGO_HOST=inventory_mongo
    networks:
      - spaceship_network
    depends_on:
      - inventory_db

volumes:
  inventory_mongo_data:

networks:
  spaceship_network:
    external: true
    name: spaceship_network