name: Run Unit Tests

on:
  workflow_call:
    inputs:
      modules:
        required: true
        type: string
      go-version:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    # Запускаем контейнер с MongoDB рядом с контейнером тестов
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        # Ждем, пока Mongo успешно стартует, прежде чем запускать шаги
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: secretpassword
        options: >-
          --health-cmd "echo 'db.runCommand({ping:1})' | mongosh localhost:27017 --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Install Task
        uses: arduino/setup-task@v2.0.0

      - name: Run tests
        run: task test
